### ISSUE TITLE
Tiny HTML5 Issues

### ISSUE THREAD

**Issue by BrazenlyGeek** [yoarts/flat#58]
There are a few things that can be done to improve HTML5 output in Flat.

* All URLs in attributes (such as in the `LINK` tags in `flat_custom_font()`) should be run through `esc_url()` or at the least `urlencode()`. The pipe character, for example, in Google font links, needs to be encoded; as it is, it throws in error in HTML5 validation.

* `type/javascript` and `type/css` are redundant on scripts and styles in HTML5, so the `type` attribute can be nixed throughout.

(It should be noted, though, that all scripts/styles should be ran through WordPress' enqueue system, so that all attributes can be managed by filtering it. Google font links in Flat are currently hardcoded and output via a hook, rather than being queued up for WP to handle.)

**Comment by thanhluu** [comment]
I have tried `urlencode()` solution. But It will have an issue when include multiple fonts.
