### ISSUE TITLE
Popover broken

### ISSUE THREAD

**Issue by gaetan-petit** [yoarts/flat#65]
**Version** : 1.5.4
**Description**:
Responsive menu not working anymore. They do work in the [theme demo](http://demo.yoarts.com/flatblog/), but not on [yoarts.com](http://www.yoarts.com/blog/wordpress/free-flat-design-wordpress-theme.html).
**Error**:
In console ```Uncaught Error: Popover requires tooltip.js```.

**Comment by thanhluu** [comment]
This issue has been fixed after this commit: https://github.com/yoarts/flat/commit/741227059b3c0040f71ce720bca84a24b9a739f3
Please wait to the next release to apply this fix.
Regards
