### ISSUE TITLE
v1.5.6 update:  Undefined hook(s) break loop

### ISSUE THREAD

**Issue by GeneDieken** [yoarts/flat#79]
Link supplied by WordPress to update Flat to 1.5.6 breaks the page loop when installed and yields this: Fatal error: Call to undefined function flat_hook_page_before() in /home/xxxxx.biz/dev/wp-content/themes/flat/page.php on line 2

Thanks for fixing the off-canvas nav buttons, though!

**Comment by thanhluu** [comment]
I have fixed this issue on Flat 1.5.7
You can download the quick fix here: https://wordpress.org/themes/download/flat.1.5.7.zip
