### ISSUE TITLE
Theme Version 1.5.6 - Pages not working

### ISSUE THREAD

**Issue by florianbeer** [yoarts/flat#82]
Opening a WordPress page gives the following error and doesn't display any content:

PHP Fatal error:  Call to undefined function flat_hook_page_before() in /var/www/blog/wp-content/themes/flat/page.php on line 2

It seems like all flat_page_* methods disappeared from this release (although they are still here in the master branch). When I re-insert those few lines into inc/hooks.php WordPress pages continue to function as before.

**Comment by thanhluu** [comment]
@florianbeer I have added those functions to Flat 1.5.7. This version is being reviewed and will be available soon.
Thanks for your report!
Regards
Thanh Luu
