### ISSUE TITLE
Color coordination fix on posts?

### ISSUE THREAD

**Issue by k4kfh** [yoarts/flat#92]
I have a site done with Flat, and it works well, but the post color scheme could use some work. My site is primarily red/white, but there is a giant section of blue on the bottom of the posts (linking to next/previous posts) could we have this color easily changeable from Wordpress so CSS editing isn't required?

**Comment by rodica-andronache** [comment]
Hi @k4kfh,

We have an add-on with 5 color schemes to choose from for Flat: http://themeisle.com/plugins/flat-plus/.
So, unfortunately we don't plan to add a color option in Flat for that color. 
The only other solution would be adding some CSS code with a plugin like this: https://wordpress.org/plugins/advanced-css-editor/

`.single .post-navigation {
  background:red;
}`

where you need to change red with the color you need.
