### ISSUE TITLE
Align center class not working

### ISSUE THREAD

**Issue by UVLabs** [yoarts/flat#94]
If you try to add an image to the site and try centering it from the center text option in the WP editor it does not actually center it.

This is because the .align-center class created by flat.min.css does not have `display: block` so please add it so text align could work @rodica-andronache @claudiuvertistudio

**Comment by rodica-andronache** [comment]
@UVLabs the correct repository for Flat is this https://github.com/Codeinwp/FlatX.
Please move the issue there, if it's still not fixed
