### ISSUE TITLE
Flat conflict with Easy Custom Auto Excerpt plugin

### ISSUE THREAD

**Issue by mileamadalin** [yoarts/flat#97]
@rodica-andronache The Flat theme have a conflict with  Easy Custom Auto Excerpt plugin.

Here is the message from the customer:

"
Fatal error: Cannot redeclare modify_read_more_link() (previously declared in /home/rekinet/domains/patrykdoering.pl/public_html/wp-content/themes/flat/functions.php:307) in /home/rekinet/domains/patrykdoering.pl/public_html/wp-content/plugins/easy-custom-auto-excerpt/easy-custom-auto-excerpt.php on line 56
"

Let me know if you can fix it.

**Comment by rodica-andronache** [comment]
@mileamadalin this is the repo https://github.com/Codeinwp/FlatX/ where we are working on flat
